### PR TITLE
fix: MCP error because types are not enforced.

### LINKED ISSUE #2421: mcp: regression in get_vulnerability_details in v2.3.1
get_vulnerability_details in v2.3.1 crashes, here's a stack trace:

```
panic: interface conversion: interface {} is **osvschema.Vulnerability, not *osvschema.Vulnerability

goroutine 183 [running]:
github.com/google/osv-scanner/v2/cmd/osv-scanner/mcp.handleVulnIDRetrieval({0x101f7f7b0, 0x140000b3ad0}, 0x30?, 0x14000705980)
	github.com/google/osv-scanner/v2/cmd/osv-scanner/mcp/command.go:171 +0x20c
github.com/modelcontextprotocol/go-sdk/mcp.toolForErr[...].func1(0x14000d43188)
	github.com/modelcontextprotocol/go-sdk@v1.1.0/mcp/server.go:290 +0x198
github.com/modelcontextprotocol/go-sdk/mcp.(*Server).callTool(0x3?, {0x101f7f7b0, 0x140000b3ad0}, 0x14000d43188)
	github.com/modelcontextprotocol/go-sdk@v1.1.0/mcp/server.go:573 +0x138
github.com/modelcontextprotocol/go-sdk/mcp.init.serverMethod[...].func19(0xa?)
	github.com/modelcontextprotocol/go-sdk@v1.1.0/mcp/shared.go:305 +0x44
github.com/modelcontextprotocol/go-sdk/mcp.newServerMethodInfo[...].func2({0x140005001f0?, 0xa?}, {0x101f80050?, 0x14000d43188?})
	github.com/modelcontextprotocol/go-sdk@v1.1.0/mcp/shared.go:261 +0x48
github.com/modelcontextprotocol/go-sdk/mcp.defaultReceivingMethodHandler[...]({0x101f7f7b0?, 0x140000b3ad0}, {0x140005001f0, 0xa}, {0x101f80050, 0x14000d43188})
	github.com/modelcontextprotocol/go-sdk@v1.1.0/mcp/shared.go:141 +0xc8
github.com/modelcontextprotocol/go-sdk/mcp.handleReceive[...]({0x101f7f7b0, 0x140000b3ad0}, 0x14000c5e000, 0x1400017f040)
	github.com/modelcontextprotocol/go-sdk@v1.1.0/mcp/shared.go:158 +0x198
github.com/modelcontextprotocol/go-sdk/mcp.(*ServerSession).handle(0x14000c5e000, {0x101f7f7b0, 0x140000b3a70}, 0x1400017f040)
	github.com/modelcontextprotocol/go-sdk@v1.1.0/mcp/server.go:1145 +0x25c
github.com/modelcontextprotocol/go-sdk/internal/jsonrpc2.HandlerFunc.Handle(0x0?, {0x101f7f7b0?, 0x140000b3a70?}, 0x0?)
	github.com/modelcontextprotocol/go-sdk@v1.1.0/internal/jsonrpc2/jsonrpc2.go:84 +0x38
github.com/modelcontextprotocol/go-sdk/internal/jsonrpc2.(*Connection).handleAsync.func3()
	github.com/modelcontextprotocol/go-sdk@v1.1.0/internal/jsonrpc2/conn.go:696 +0x64
created by github.com/modelcontextprotocol/go-sdk/internal/jsonrpc2.(*Connection).handleAsync in goroutine 182
	github.com/modelcontextprotocol/go-sdk@v1.1.0/internal/jsonrpc2/conn.go:694 +0x19c
```

I also confirmed v2.2.4 works. 

Looking at changelogs, likely related to "new internal data models"?

### PR DESCRIPTION
**Pull request by another-rex**
Fixes #2421 

Also:
- fixes schema validation issue which could appear if there is additional data in database specific.
- adds integration tests to confirm all the tools works correctly.
- Add GOTOOLCHAIN default to run_lints.sh to allow linter to run when system go version is older than expected.

### CODE REVIEW

File: scripts/run_lints.sh [hunk 1]
```diff
@@ -2,4 +2,4 @@
 
 set -ex
 
-go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.1 run ./...
+GOTOOLCHAIN=go1.25.5 go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.1 run ./... $@
```
Comment (cuixq) [inline scripts/run_lints.sh]: is this intended? this will probably override the environment variable specified in a command.

File: cmd/osv-scanner/mcp/integration_test.go [hunk 2]
```diff
@@ -0,0 +1,209 @@
...
+			t.Fatalf("expected TextContent, got %T", scanResult.Content[0])
+		}
+
+		output := textRes.Text
+		t.Logf("Scan completed. Output length: %d", len(output))
+		testutility.NewSnapshot().MatchText(t, output)
+
+		// Extract a vulnerability ID for the next step.
+		// Example: GHSA-f682-3w9h-r22r or GO-2023-1558
+		re := cachedregexp.MustCompile(`(GHSA-[a-zA-Z0-9-]+|GO-\d{4}-\d+)`)
```
Comment (cuixq) [inline cmd/osv-scanner/mcp/integration_test.go]: is this over complicated? since we are testing against the test Go project - should we know about the vulnerabilities in this project already?

File: scripts/run_lints.sh (hunk 1 above)
Comment (another-rex) [reply scripts/run_lints.sh]: This is intended, though good point about it overriding, fixed now. Right now on our machines run_lint script won't work because it uses the system's go version rather than the projects go version.

File: cmd/osv-scanner/mcp/integration_test.go (hunk 2 above)
Comment (another-rex) [reply cmd/osv-scanner/mcp/integration_test.go]: Sort of? I wanted new vulnerabilities to show up automatically, but I guess the current version doesn't really allow that either. I'll switch it to a hard coded value.

File: cmd/osv-scanner/mcp/integration_test.go [hunk 3]
```diff
@@ -0,0 +1,205 @@
...
+		}
+
+		output := textRes.Text
+		t.Logf("Scan completed. Output length: %d", len(output))
+		testutility.NewSnapshot().MatchText(t, output)
+
+		vulnID = "GO-2023-1558"
+	})
+
+	if vulnID == "" {
```
Comment (cuixq) [inline cmd/osv-scanner/mcp/integration_test.go]: this is redundant now?

**Review by cuixq — APPROVED** [review]

File: cmd/osv-scanner/mcp/integration_test.go (hunk 3 above)
Comment (another-rex) [reply cmd/osv-scanner/mcp/integration_test.go]: Ah good point, removed.

File: cmd/osv-scanner/mcp/command.go [hunk 4]
```diff
@@ -166,20 +170,35 @@ type getVulnerabilityDetailsInput struct {
...
 		vuln, err = osvdev.DefaultClient().GetVulnByID(ctx, input.VulnID)
 		if err != nil {
 			return nil, nil, fmt.Errorf("vulnerability with ID %s not found: %w", input.VulnID, err)
 		}
 
-		vulnCacheMap.Store(input.VulnID, vuln)
+		vulnCacheMu.Lock()
+		vulnCacheMap[input.VulnID] = vuln
+		vulnCacheMu.Unlock()
+	}
```
[the remark this answers is not in the document]
Comment (another-rex) [reply cmd/osv-scanner/mcp/command.go:187]: Good point, but by it's nature as a MCP server it's highly unlikely the same vulnID is called multiple times, and the cache is mostly for caching the original response from the scan.
