### PR TITLE
fix: use global logger in cmdlogger when set

### LINKED ISSUE #2081: Allow configuration of the library's logging
The OpenSSF Scorecard project uses osv-scanner as a library, specifically `osvscanner.DoScan`. I experimented briefly with the migration to v2 recently and started getting a flood of logs to our stderr which are originating from osv-scanner.

```
2025/07/16 11:03:49 INFO Scanning dir <...>
2025/07/16 11:04:15 ERROR Error during extraction: (extracting as java/pomxmlnet) failed resolving
2025/07/16 11:04:39 INFO Scanned <...>/package-lock.json file and found 1568 packages
```

Is there anyway to introduce a control to disable `cmdlogger`'s output? It seems most of the codebase uses `cmdlogger.Info` (and friends), which write to the default (global) slog handler.
https://github.com/google/osv-scanner/blob/6515dc09a74355444b56c7dbf85b025bf9161b94/internal/cmdlogger/fmt.go#L8-L22

I can set the slog default to something which would ignore it, like [slog.DiscardHandler](https://pkg.go.dev/log/slog#DiscardHandler), but this would break many of our own logging.

### PR DESCRIPTION
**Pull request by spencerschrock**
Previously this code would always use the default slog handler, even if a user called `osvscanner.SetLogger`.

Also set osv-scalibr logger to same global logger. A small adapter was needed since osv-scalibr has its own logging interface.

Fixes #2081

### CODE REVIEW

File: internal/cmdlogger/handler.go [hunk 1]
```diff
@@ -8,7 +8,10 @@ import (
 	"strings"
 )
 
-var GlobalHandler slog.Handler
+var (
+	GlobalHandler slog.Handler
+	GlobalLogger  *slog.Logger
+)
```
Comment (spencerschrock) [inline internal/cmdlogger/handler.go]: also happy to do this here if you want to avoid the `cmp.Or` and `slog.Default` calls in fmt.go:
```
GlobalLogger = slog.Default
```

**Comment by spencerschrock** [comment]
> Also set osv-scalibr logger to same global logger. A small adapter was needed since osv-scalibr has its own logging interface.

The adapter and the call to osv-scalibr/log.SetLogger could live in Scorecard if needed, it just seemed applicable for a library logger to also set its libraries loggers.

**Comment by another-rex** [comment]
Hmm... I'm not sure why the previous version was not working for you. We need the custom handler to set the correct error code when printing an error message, then redirect to the new handler.

**Comment by another-rex** [comment]
Ah I see we are not setting the slog.handler in DoScan()

**Comment by another-rex** [comment]
Looked at my original fix again, I'm not sure why I thought that will work 🤦. Thanks for the fix! I updated it a bit to fulfill the original intent of the GlobalHandler override, and added a test to verify.
