### PR TITLE
fix: ensure that vulnerability results are ordered deterministically

### LINKED ISSUE #182: Make output ordering deterministic
Currently, it looks like the order of the package source files (in every output format) can change between runs.

e.g.
```
# Output 1
╭─────────────────────────────────────┬───────────┬──────────────────────────┬─────────┬────────────────────╮
│ OSV URL (ID IN BOLD)                │ ECOSYSTEM │ PACKAGE                  │ VERSION │ SOURCE             │
├─────────────────────────────────────┼───────────┼──────────────────────────┼─────────┼────────────────────┤
│ https://osv.dev/GHSA-m5pq-gvj9-9vr8 │ crates.io │ regex                    │ 1.3.1   │ path/to/Cargo.lock │
│ https://osv.dev/RUSTSEC-2022-0013   │           │                          │         │                    │
│ https://osv.dev/GHSA-c3h9-896r-86jm │ Go        │ github.com/gogo/protobuf │ 1.3.1   │ path/to/go.mod     │
│ https://osv.dev/GO-2021-0053        │           │                          │         │                    │
╰─────────────────────────────────────┴───────────┴──────────────────────────┴─────────┴────────────────────╯

# Output 2
╭─────────────────────────────────────┬───────────┬──────────────────────────┬─────────┬────────────────────╮
│ OSV URL (ID IN BOLD)                │ ECOSYSTEM │ PACKAGE                  │ VERSION │ SOURCE             │
├─────────────────────────────────────┼───────────┼──────────────────────────┼─────────┼────────────────────┤
│ https://osv.dev/GHSA-c3h9-896r-86jm │ Go        │ github.com/gogo/protobuf │ 1.3.1   │ path/to/go.mod     │
│ https://osv.dev/GO-2021-0053        │           │                          │         │                    │
│ https://osv.dev/GHSA-m5pq-gvj9-9vr8 │ crates.io │ regex                    │ 1.3.1   │ path/to/Cargo.lock │
│ https://osv.dev/RUSTSEC-2022-0013   │           │                          │         │                    │
╰─────────────────────────────────────┴───────────┴──────────────────────────┴─────────┴────────────────────╯
```
(this can also happen in the json output)

From what I can tell, this only affects the ordering of package sources - the ordering of packages from a source, and vulnerabilities in a package seem to be consistent between runs.

### PR DESCRIPTION
**Pull request by G-Rath**
Resolves #182

### CODE REVIEW

File: cmd/osv-scanner/main_test.go [hunk 1]
```diff
@@ -352,6 +352,30 @@ func TestRun_LockfileWithExplicitParseAs(t *testing.T) {
 			`,
 			wantStderr: "",
 		},
+		// multiple, + output order is deterministic
```
Comment (another-rex) [inline cmd/osv-scanner/main_test.go:355]:
```suggestion
		// multiple, + output order is deterministic
		{
			name: "",
			args: []string{
				"",
				"-L", "yarn.lock:" + filepath.FromSlash("./fixtures/locks-insecure/my-yarn.lock"),
				"-L", "package-lock.json:" + filepath.FromSlash("./fixtures/locks-insecure/my-package-lock.json"),
				filepath.FromSlash("./fixtures/locks-insecure"),
			},
			wantExitCode: 1,
			wantStdout: `
				Scanned %%/fixtures/locks-insecure/my-yarn.lock file as a yarn.lock and found 1 packages
				Scanned %%/fixtures/locks-insecure/my-package-lock.json file as a package-lock.json and found 1 packages
				Scanning dir ./fixtures/locks-insecure
				Scanned %%/fixtures/locks-insecure/composer.lock file and found 0 packages
				+-------------------------------------+-----------+-----------+---------+----------------------------------------------+
				| OSV URL (ID IN BOLD)                | ECOSYSTEM | PACKAGE   | VERSION | SOURCE                                       |
				+-------------------------------------+-----------+-----------+---------+----------------------------------------------+
				| https://osv.dev/GHSA-whgm-jr23-g3j9 | npm       | ansi-html | 0.0.1   | fixtures/locks-insecure/my-package-lock.json |
				| https://osv.dev/GHSA-whgm-jr23-g3j9 | npm       | ansi-html | 0.0.1   | fixtures/locks-insecure/my-yarn.lock         |
				+-------------------------------------+-----------+-----------+---------+----------------------------------------------+
			`,
			wantStderr: "",
		},
```

Add another test with the two outputs swapped, the table output should remain the same, while the scanning order changes.

**Review by another-rex — APPROVED** [review]
LGTM, just suggested adding another test with the orders swapped.
