### PR TITLE
fix: correctly output packages from osv-scanner.json source in spdx format

### LINKED ISSUE #2192: Scanning `osv-scanner.json` format does not correctly output spdx
Scanning `osv-scanner.json` format does not correctly output with the `--format=spdx` flag. 

Currently no packages will appear, and after #2177 it will show up with the incorrect purl type.

### PR DESCRIPTION
**Pull request by Mananshah237**
Fixes #2192

Packages loaded from an `osv-scanner.json` results file have `Inventory == nil`
because `PackageInfo.Inventory` is not populated during JSON deserialization.

`PrintSPDXResults` was blindly appending nil Inventory values, causing the
SPDX converter to silently skip all such packages.

This fix constructs a synthetic `extractor.Package` using the available
PackageInfo fields (name, version, ecosystem) when Inventory is nil.

Maven packages require special handling because their names are stored as
`groupId:artifactId` in osv-scanner. The scalibr PURL converter requires
`javalockfile.Metadata` with `GroupID` and `ArtifactID` to generate the correct
`pkg:maven/groupId/artifactId@version` PURL.

This ensures packages from osv-scanner.json sources appear correctly
in the generated SPDX SBOM output.

### CODE REVIEW

File: internal/output/spdx.go [hunk 1]
```diff
@@ -27,3 +39,38 @@ func PrintSPDXResults(vulnResult *models.VulnerabilityResults, outputWriter io.W
 
 	return encoder.Encode(doc)
 }
+
+// inventoryFromPackageInfo constructs a synthetic extractor.Package from a PackageInfo
+// for packages that don't have a populated Inventory field (e.g., loaded from osv-scanner.json).
+func inventoryFromPackageInfo(pkg models.PackageInfo) *extractor.Package {
```
Comment (another-rex) [inline internal/output/spdx.go]: Have this function return an error as well, rather than just nil, to be handled in the caller.

**Review by another-rex — COMMENTED** [review]
Nice, pretty neat fix!

Just need to fix the linting issues and one comment, otherwise LGTM.

**Review by another-rex — APPROVED** [review]
