### PR TITLE
fix: warn about and ignore duplicate entries in SBOMs

### LINKED ISSUE #330: Duplicate results
When parsing a hierarchical CycloneDX SBOM, there is the possibility of duplicate references to some components. These are evaluated (?) and reported multiple times, without a way to differentiate them (or trace the to the originating component).

The result represented by `osv-scanner` should:
- [ ] not contain duplicate entries, and
- [ ] allow to see, where the faulty component originates (ie. present a component tree like `npm audit` or `cargo audit`)

### PR DESCRIPTION
**Pull request by G-Rath**
While from what I understand duplicates should not be possible in a valid SBOM, apparently they happen and it's useful for us to report + skip them.

Since doing this efficiently requires use of a map we in turn have to sort the packages to ensure a consistent output order, leading to me discovering that we're not already sorting the packages - I've opened #1288 to land that change first.

Resolves #330

### CODE REVIEW

File: pkg/osvscanner/osvscanner.go [hunk 1]
```diff
@@ -515,11 +520,17 @@ func scanSBOMFile(r reporter.Reporter, path string, fromFSScan bool) ([]scannedP
 				}
 			}
 
-			slices.SortFunc(packages, func(i, j scannedPackage) int {
+			packages2 := make([]scannedPackage, 0, len(packages))
```
Comment (cuixq) [inline pkg/osvscanner/osvscanner.go:523]: rename `packages` and `packages2` to something indicating one is a map and one is a slice.

**Review by cuixq — APPROVED** [review]

**Review by another-rex — APPROVED** [review]
